### ISSUE TITLE
Some troubles

### ISSUE THREAD

**Issue by ss1user** [ajobi/batch-image-editor#1]
1. The main problem is trouble with multi fill images. Changing in plugin don't work. https://tppr.me/DFkIN2
2. I know, that is t2 hard for dev, but I expect reading of current parameters of filter https://tppr.me/CHd4E

thx

**Comment by ajobi** [comment]
@ss1user hi! thanks for posting the issue 👌 
1. The screenshot you posted does not work anymore, what is the functionality you would expect? Can you explain a bit more?
2. This probably cannot work. If you batch edit images each one of them can have different filter parameters applied already and they would conflict with each other.
